# Generated by Django 4.1.5 on 2023-02-13 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('littleLemon', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='cuisine',
            new_name='cook',
        ),
    ]
