# Generated by Django 4.1.5 on 2023-03-06 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('littleLemon', '0002_rename_cuisine_menu_cook'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
